version: "3"

services:
  db:
    image: "mysql:latest"
    container_name: "letscard-mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "letscard-tomcat"
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - db
    depends_on:
      - db

volumes:
  mysql-data: